#!/bin/bash

Rscript /home/rahumada/scripts/main_helada.R $(date +%F) 58 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 60 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 62 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 63 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 74 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 76 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 77 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 79 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 82 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 83 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 84 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 86 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 88 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 89 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 90 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 91 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 92 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 93 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 94 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 95 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 97 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 98 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 99 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 100 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 101 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 102 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 103 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 104 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 105 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 164 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 165 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 166 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 167 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 168 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 169 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 229 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 238 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 239 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 240 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 241 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 242 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 244 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 252 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 253 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 254 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 291 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 292 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 293 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 305 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 311 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 312 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 368 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 403 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 408 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 413 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 491 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 495 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 503 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 592 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 597 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 625 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 628 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 198 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 118 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 316 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 124 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 128 15
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 523 15
