#!/bin/bash
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 58 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 60 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 62 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 63 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 74 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 76 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 77 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 79 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 82 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 83 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 84 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 86 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 88 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 89 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 90 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 91 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 92 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 93 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 94 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 95 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 97 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 98 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 99 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 100 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 101 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 102 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 103 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 104 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 105 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 164 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 165 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 166 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 167 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 168 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 169 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 229 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 238 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 239 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 240 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 241 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 242 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 244 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 252 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 253 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 254 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 291 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 292 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 293 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 305 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 311 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 312 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 368 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 403 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 408 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 413 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 491 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 495 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 503 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 592 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 597 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 625 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 628 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 198 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 118 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 316 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 124 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 128 18
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 523 18
