#!/bin/bash
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 58 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 60 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 62 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 63 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 74 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 76 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 77 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 79 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 82 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 83 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 84 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 86 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 88 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 90 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 91 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 89 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 92 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 93 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 94 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 95 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 97 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 98 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 99 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 100 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 101 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 102 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 103 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 104 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 105 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 164 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 165 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 166 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 167 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 168 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 169 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 229 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 238 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 239 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 240 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 241 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 242 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 244 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 252 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 253 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 254 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 291 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 292 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 293 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 305 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 311 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 312 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 368 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 403 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 408 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 413 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 491 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 495 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 503 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 592 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 597 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 625 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 628 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 198 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 118 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 316 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 124 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 128 21
Rscript /home/rahumada/scripts/main_helada.R  $(date +%F) 523 21
